name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      
      - name: Check pdf file
        run: |
          file main.pdf | grep -q ' PDF '
      
      - name: Upload pdf document
        uses: actions/upload-artifact@v2
        with:
          #       
          name: my_doc
          #    pdf.   «*», «**»
          #   <working_directory>/<jobname>.pdf
          path: latex_sources/my_doc.pdf
